[package]
name = "music"
version = "0.1.0"
edition = "2021"

[dependencies]
audio = { path = "../audio" }
common = { path = "../common" }
rustysynth = "1"
sevenz-rust2 = { version = "0.23", default-features = false }

[dev-dependencies]
sevenz-rust2 = { version = "0.23", default-features = false, features = ["compress", "util"] }
