pub mod ability_prediction;
pub mod action_bar;
pub mod actor;
pub mod actor_dead_visibility;
pub mod animator;
pub mod attack_telegraph;
pub mod camera;
pub mod character_panel;
pub mod combat;
pub mod combat_ui;
// pub mod effect;
pub mod input;
// pub mod prediction; // REMOVED: Client-side attack prediction removed
pub mod renet;
pub mod resource_bars;
pub mod target_frame;
pub mod target_indicator;
pub mod targeting;
pub mod threat_icons;
pub mod tier_lock_range_indicator;
pub mod ui;
pub mod world;
