[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2", default-features = false, features = ["std", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
socket2 = { version = "0.5", features = ["all"] }
tinyvec = { version = "1.10.0", features = ["rustc_1_55", "serde"] }

[build-dependencies]
serde_json = "1"
